package com.igorjoz.shop;

import jakarta.persistence.*;
import lombok.*;
import java.io.Serializable;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "categories") // Table name in plural form, snake_case
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
@ToString(exclude = "products")
public class Category implements Comparable<Category>, Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "id", columnDefinition = "BINARY(16)")
    private UUID id; // UUID generated by the client

    @Column(name = "name")
    private String name;

    @Column(name = "order_in_shop")
    private int orderInShop;

    // Bidirectional relationship; fetch type is LAZY to avoid fetching products by default
    @OneToMany(mappedBy = "category", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Product> products;

    @Override
    public int compareTo(Category other) {
        return this.name.compareTo(other.name);
    }
}
